# action.yml
name: "Hello World"
description: "Greet someone and record the time"
inputs:
  schema-file:
    default: "schema.yml"
    description: "schema files used for validation"
    required: true
  test-file:
    default: "action.yml"
    required: true
    description: "yaml file that needs to be validated"
outputs:
  time: # id of output
    description: "The time of validation"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.schema-file }}
    - ${{ inputs.test-file }}
