# action.yml
name: "python-yamale"
description: "A schema and validator for YAML."
inputs:
  schema-file:
    default: "schema.yml"
    description: "schema files used for validation"
    required: true
  test-file:
    default: "action.yml"
    required: true
    description: "yaml file that needs to be validated"
  strict:
    default: "strict"
    required: false
    description: "strict|nonstrict validation is requred"

outputs:
  time: # id of output
    description: "The time of validation"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.schema-file }}
    - ${{ inputs.test-file }}
    - ${{ inputs.strict}}
